'use client';
import React,{useId,useState} from 'react';
import {calculateSimpleGoal,type SimpleGoalInputs} from '@/lib/growthKpi';
import {GROWTH_MEASUREMENT,GROWTH_SOURCES} from '@/lib/growthKnowledge';
const empty=():SimpleGoalInputs=>({opportunities:'',completed:'',targetCompleted:''});
const format=(n:number)=>n.toLocaleString('ko-KR',{maximumFractionDigits:2});
export default function GrowthKpiPanel({targetUrl}:{targetUrl:string}) {
 const id=useId();
 const [mode,setMode]=useState<'conversion'|'search'>('conversion'),[inputs,setInputs]=useState(empty),[demo,setDemo]=useState(false),[channel,setChannel]=useState('Google 자연 검색'),[period,setPeriod]=useState('최근 28일'),[status,setStatus]=useState(''),[fallback,setFallback]=useState('');
 const result=calculateSimpleGoal(inputs),search=mode==='search',unit=search?'검색 노출':'방문',done=search?'검색 클릭':'문의·구매 완료';
 const labels={opportunities:search?'현재 검색 노출수':'현재 방문 횟수',completed:search?'현재 검색 클릭수':'문의·구매가 완료된 방문 횟수',targetCompleted:search?'원하는 검색 클릭수':'목표로 하는 완료 방문 횟수'};
 const helps={opportunities:search?'검색 결과에 페이지가 표시된 횟수':'GA4의 세션 수를 입력하세요.',completed:search?'위 노출과 같은 기간의 클릭수':'같은 방문에서 여러 번 문의해도 1회로 셉니다.',targetCompleted:'같은 길이의 기간에 달성하고 싶은 목표'};
 function update(key:keyof SimpleGoalInputs,value:string){setInputs(previous=>({...previous,[key]:value}));setStatus('');setFallback('');}
 async function copy(){const text=[`${demo?'가상 예시':'직접 입력'} · ${done} 목표 계산`,targetUrl,`${channel} · ${period}`,`현재 ${unit}: ${inputs.opportunities} / 완료: ${inputs.completed}`,`목표 완료: ${inputs.targetCompleted}`,`현재 비율 ${result.rate===null?'미계산':format(result.rate*100)+'%'}가 유지되면 필요한 ${unit}: ${result.required===null?'계산 불가':format(result.required)}`,'현재 비율이 유지된다는 가정의 계산입니다. 수정 효과나 성과 예측이 아닙니다.'].join('\n');try{await navigator.clipboard.writeText(text);setStatus('계산 내용을 복사했습니다.');setFallback('');}catch{setStatus('아래 내용을 직접 복사하세요.');setFallback(text);}}
 return <section className="report-card report-growth-kpi" aria-label="간단 목표 계산기">
  <div className="report-card-heading"><p className="report-eyebrow">목표 계산</p><h3>목표를 이루려면 방문이 얼마나 필요할까요?</h3><p className="report-note">현재 수치 2개와 목표 1개만 입력하세요. 지금의 완료 비율이 그대로 유지된다는 가정으로 계산합니다.</p></div>
  <div className="work-tabs simple-kpi-tabs" role="group" aria-label="계산할 목표 선택">{[['conversion','문의·구매 목표'],['search','검색 클릭 목표']].map(([key,label])=><button type="button" key={key} aria-pressed={mode===key} onClick={()=>{setMode(key as typeof mode);setChannel('Google 자연 검색');setInputs(empty());setDemo(false);setStatus('');setFallback('');}}>{label}</button>)}</div>
  <div className="simple-kpi-help"><strong>처음이라면 예시부터 눌러 보세요.</strong><p>{search?'10,000번 노출되어 300번 클릭됐다면, 같은 비율로 450번 클릭받으려면 15,000번 노출이 필요합니다.':'1,000번 방문 중 20번 문의가 완료됐다면, 같은 비율로 30번 완료되려면 1,500번 방문이 필요합니다.'}</p><button type="button" className="report-secondary-button" onClick={()=>{setInputs(search?{opportunities:'10000',completed:'300',targetCompleted:'450'}:{opportunities:'1000',completed:'20',targetCompleted:'30'});setDemo(true);setStatus('');setFallback('');}}>예시 숫자로 계산해 보기</button></div>
  <div className="growth-kpi-context"><label>어느 유입을 비교하나요?<select value={channel} onChange={e=>{setChannel(e.target.value);setStatus('');setFallback('');}}><option>Google 자연 검색</option><option>네이버 웹 자연 검색</option>{!search&&<><option>전체 유입</option><option>AI 서비스 유입</option></>}</select></label><label>집계 기간<input value={period} maxLength={100} onChange={e=>{setPeriod(e.target.value);setStatus('');setFallback('');}} placeholder="예: 수정 전 28일"/></label></div>
  {demo&&<p className="simple-kpi-demo" role="status">예시에서 시작한 계산입니다. 실제 사이트 실적이 아닙니다. 내 수치를 넣으려면 ‘내 수치 입력’을 누르세요.</p>}
  <div className="simple-kpi-fields">{(Object.keys(labels) as (keyof SimpleGoalInputs)[]).map((key,i)=><label htmlFor={`${id}-${key}`} key={key}><span><b>{i+1}</b>{labels[key]}</span><input id={`${id}-${key}`} type="number" inputMode="numeric" min="0" max="1000000000000" step="1" value={inputs[key]} placeholder="숫자 입력" aria-invalid={!!result.errors[key]} aria-describedby={`${id}-${key}-help`} onChange={e=>update(key,e.target.value)}/><small id={`${id}-${key}-help`}>{result.errors[key]||helps[key]}</small></label>)}</div>
  <div className="simple-kpi-result" aria-live="polite" aria-atomic="true">{result.required!==null&&result.rate!==null?<><span>{demo?'가상 예시 · ':''}현재 {done} 비율 {format(result.rate*100)}%가 유지된다면</span><h4>필요한 {unit} <strong>{format(result.required)}회</strong></h4><p>{result.additional!>0?`현재보다 ${format(result.additional!)}회가 더 필요합니다.`:result.additional===0?'현재 횟수와 같은 규모입니다.':'입력한 현재 횟수보다 낮은 목표입니다.'}</p></>:<><h4>위의 숫자 3개를 입력하면 결과가 나옵니다.</h4><p>{Object.keys(result.errors).length?'표시된 입력 오류를 먼저 확인해 주세요.':result.values.completed===0?'완료가 0회이면 현재 비율로 필요한 횟수를 계산할 수 없습니다. 완료가 발생한 기간의 수치를 사용하세요.':'비율(%)은 직접 입력할 필요가 없습니다.'}</p></>}</div>
  <p className="report-note">사이트 수정으로 비율이 얼마나 달라질지는 계산하지 않습니다. 같은 기간·채널·완료 기준의 수치를 사용하세요.</p>
  <div className="growth-kpi-controls"><button type="button" className="report-secondary-button" onClick={()=>{setInputs(empty());setDemo(false);setStatus('');setFallback('');}}>내 수치 입력 · 비우기</button><button type="button" className="report-secondary-button" disabled={result.required===null||result.rate===null} onClick={copy}>계산 내용 복사</button></div><p role="status">{status}</p>{fallback&&<label className="growth-copy-fallback">직접 복사할 계산 내용<textarea readOnly value={fallback} rows={8}/></label>}
  <p className="report-note">입력값은 이 화면에서만 유지됩니다. 필요한 내용은 복사해서 보관하세요.</p>
  <details className="growth-measurement"><summary>숫자는 어디서 확인하나요?</summary><div>{GROWTH_MEASUREMENT.filter(m=>search?/Search Console|서치어드바이저|검색/.test(m.where):/GA4|애널리틱스/.test(m.where)).map(m=><article key={m.title}><h4>{m.title}</h4><strong>{m.where}</strong><p>{m.metric}</p><p>{m.note}</p><a href={GROWTH_SOURCES[m.source].url} target="_blank" rel="noopener noreferrer">공식 측정 가이드 ↗</a></article>)}</div></details>
 </section>;
}
