"use client";
import React,{useState} from 'react';
import EvidenceFlow from './EvidenceFlow';
import ReportJumpLink from './ReportJumpLink';
import {Guidebook} from './SiteGuidebook';
import DiagnosisIcon from './DiagnosisIcon';
import {contentBrief,insightNotes,messageThemes,type ReportInsights} from '@/lib/reportInsights';

function Heading({label,title,note}:{label:string;title:string;note?:string}) {return <div className="report-card-heading"><p className="report-eyebrow">{label}</p><h3>{title}</h3>{note&&<p className="report-note">{note}</p>}</div>;}
function Empty({children}:{children:React.ReactNode}) {return <p className="report-empty">{children}</p>;}
function Link({url,children}:{url:string;children:React.ReactNode}) {return <a className="report-source-link" href={url} target="_blank" rel="noopener noreferrer">{children} ↗</a>;}
export function CollectionCoverage({data}:{data:ReportInsights}) {return <article className="report-card" aria-label="데이터 수집 현황"><Heading label="DATA COVERAGE" title="어디까지 확인했나요?" note="현재 보고서에 저장된 범위입니다. 항목별 확인 범위가 다르면 미확인 상태를 함께 표시합니다."/><div className="report-four-grid">{data.coverage.map((c,i)=><div className="report-stat" key={c.label}><div className="report-stat-top"><DiagnosisIcon axis={i===0?'firstView':i===1?'seo':i===2?'trust':'adLanding'}/><span className="report-pill">{c.state}</span></div><h4>{c.label}</h4><strong>{c.value}</strong><p>{c.detail}</p></div>)}</div></article>;}
export function ConversionPath({data}:{data:ReportInsights}) {
  const lowest=Math.min(...data.stages.map(s=>s.score));
  return <article className="report-card" aria-label="고객 전환 준비도"><Heading label="CONVERSION READINESS" title="고객이 결정하기까지, 네 단계" note={insightNotes.stages}/><ol className="report-journey">{data.stages.map((s,i)=><li key={s.key} className={s.score===lowest?'is-focus':''}><div className="report-step-top"><span>0{i+1}</span>{s.score===lowest&&<b>우선 검토</b>}</div><h4>{s.label}</h4><div className="report-score"><strong>{s.score}</strong><span>/ 100</span></div><div className="report-meter" aria-hidden="true"><i style={{width:`${s.score}%`}}/></div><p>{s.action}</p></li>)}</ol></article>;
}
function CopyBrief({question,target}:{question:string;target:string|null}) {
  const [message,setMessage]=useState('');
  return <div className="report-copy"><button type="button" className="report-secondary-button" onClick={async()=>{try{await navigator.clipboard.writeText(contentBrief(question,target));setMessage('콘텐츠 작성 틀을 복사했습니다.');}catch{setMessage('복사하지 못했습니다. 브라우저의 클립보드 권한을 확인해 주세요.');}}}>콘텐츠 작성 틀 복사</button><span role="status">{message}</span></div>;
}
export function AnswerPageMap({data}:{data:ReportInsights}) {return <article className="report-card" aria-label="질문과 답변 페이지 지도"><Heading label="QUESTION → PAGE" title="질문을 어떤 페이지에서 답할까요?" note={insightNotes.questions}/>{data.questions.length?<div className="report-detail-list">{data.questions.map(q=><details key={q.question}><summary><span className="report-index">Q{q.id}</span><span className="report-summary-title">{q.question}</span><span className="report-pill">{q.kind}</span></summary><div className="report-detail-body"><p>{q.evidence}</p>{q.target&&<Link url={q.target}>{q.target}</Link>}<div className="report-brief-grid">{['직접 답변','적용 조건·범위','검증 가능한 근거','최종 확인 날짜'].map((v,i)=><div key={v}><span>0{i+1}</span><strong>{v}</strong></div>)}</div><p className="report-note">각 칸을 확인된 사실로 채운 뒤 페이지에 적용하세요. 가격·후기·성과 수치는 담당자 확인이 필요합니다.</p><CopyBrief question={q.question} target={q.target}/></div></details>)}</div>:<Empty>새 형식의 질문 관측이 저장되면 페이지 연결 후보를 표시합니다.</Empty>}</article>;}
export function BrandReview({data}:{data:ReportInsights}) {return <article className="report-card" aria-label="브랜드 답변 검토함"><Heading label="BRAND ANSWER REVIEW" title="브랜드 언급 다음에는 내용 대조" note={insightNotes.reviews}/><div className="report-inline-stat"><strong>{data.obs?data.reviews.length:'—'}</strong><span>대조 대상 답변</span><span className="report-pill">규칙 기반 검토 제안</span></div>{data.reviews.length?<div className="report-detail-list">{data.reviews.map((r,i)=><details key={`${r.engine}-${i}`}><summary><span className="report-pill warning">내용 대조</span><span className="report-summary-title">{r.question}</span><span>{r.engine}</span></summary><div className="report-detail-body"><p className="report-note">체크 포인트: 업체명이 맞는지 → 실제 서비스인지 → 출처의 업체와 일치하는지</p><blockquote className="report-answer">{r.answer}</blockquote><div className="report-source-list">{r.sources.map(s=><Link key={s.url} url={s.url}>{s.title||s.url}</Link>)}</div></div></details>)}</div>:<Empty>{data.obs?'이 규칙에 해당하는 답변은 없습니다. 답변 전체의 정확성을 검증한 결과는 아닙니다.':'새 형식의 AI 답변 관측이 없어 대조 대상을 판정하지 않았습니다.'}</Empty>}</article>;}
export function SourceDirectory({data}:{data:ReportInsights}) {
  const [filter,setFilter]=useState('all');const [expanded,setExpanded]=useState(false);
  const filtered=data.sources.filter(s=>filter==='all'||s.ownership===filter),shown=expanded?filtered:filtered.slice(0,6);
  const names={own:'자사',external:'외부',unresolved:'도메인 미확인'};
  return <article className="report-card" aria-label="AI 출처 검토함"><Heading label="SOURCE DIRECTORY" title="AI가 근거로 연결한 페이지" note={insightNotes.sources}/><div className="report-filter-row" role="group" aria-label="출처 구분 필터">{([['all','전체'],['own','자사'],['external','외부'],['unresolved','미확인']] as const).map(([key,label])=><button type="button" key={key} aria-pressed={filter===key} onClick={()=>{setFilter(key);setExpanded(false);}}>{label}</button>)}<span role="status">{filtered.length}개 URL</span></div>{shown.length?<div className="report-source-grid">{shown.map(s=><div className="report-source-item" key={s.url}><div className="report-source-meta"><span className="report-pill">{names[s.ownership]}</span><span>{s.observations.length}건의 관측</span></div><h4><Link url={s.url}>{s.title}</Link></h4><p className="report-note">{s.domain}</p><details><summary>연결된 질문 {s.questions.length}개</summary><ul>{s.questions.map(q=><li key={q}>{q}</li>)}</ul></details></div>)}</div>:<Empty>이 조건으로 확인한 출처 URL이 없습니다.</Empty>}{filtered.length>6&&<button type="button" className="report-secondary-button mt-4" onClick={()=>setExpanded(!expanded)}>{expanded?'출처 접기':`전체 ${filtered.length}개 출처 보기`}</button>}</article>;
}
function MessageSignal({match}:{match:string|null|undefined}) {
  const state=match===undefined?'unknown':match?'found':'absent';
  return <span className={`report-message-signal is-${state}`}><svg viewBox="0 0 16 16" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><circle cx="8" cy="8" r="6.25"/>{state==='found'?<path d="m5 8 2 2 4-4"/>:state==='absent'?<path d="M5.5 8h5"/>:<><path d="M6.5 5.7a1.5 1.5 0 0 1 3 .3c0 1-1.5 1-1.5 2"/><path d="M8 10.5h.01"/></>}</svg><span>{match===undefined?'미확인':match||'미탐지'}</span></span>;
}
export function MessageMap({data}:{data:ReportInsights}) {
  return <article className="report-card" aria-label="경쟁사 메시지 비교 지도"><Heading label="MESSAGE COVERAGE" title="자사와 비교 후보가 강조하는 메시지" note={insightNotes.messages}/><div className="report-message-legend" aria-label="메시지 탐지 상태 범례"><MessageSignal match="표현 탐지"/><MessageSignal match={null}/><MessageSignal match={undefined}/></div><div className="report-table-scroll"><table className="report-message-table"><caption className="sr-only">제목·메타 설명에 저장된 메시지 표현 비교</caption><thead><tr><th scope="col">사이트</th>{messageThemes.map(t=><th scope="col" key={t.label}>{t.label}</th>)}</tr></thead><tbody>{data.messageRows.map((r,i)=><tr key={`${r.name}-${i}`} className={r.isOwn?'is-own':''}><th scope="row">{r.name}<small>{r.available?`${r.fieldCount}/2개 필드`:'수집 미확인'}</small></th>{r.cells.map(c=><td key={c.label} className={c.match?'has-match':''}><MessageSignal match={c.match}/></td>)}</tr>)}</tbody></table></div><div className="report-message-mobile">{data.messageRows.map((r,i)=><div key={`${r.name}-${i}`}><h4>{r.name} <span>{r.available?`${r.fieldCount}/2개 필드`:'수집 미확인'}</span></h4><dl>{r.cells.map(c=><div key={c.label}><dt>{c.label}</dt><dd><MessageSignal match={c.match}/></dd></div>)}</dl></div>)}</div><div className="report-callout"><strong>자사 문구에서 검토할 표현</strong>{data.messageOpportunities.length?<p>{data.messageOpportunities.map(o=>`${o.label} (${o.total}개 수집 후보 중 ${o.count}개에서 탐지)`).join(' · ')}. 실제 제공하는 가치와 맞는 항목만 검토하세요.</p>:<p>현재 저장된 제목·설명에서 제안할 공통 표현이 없거나, 비교할 정보가 충분하지 않습니다.</p>}</div><details className="report-inline-details"><summary>비교에 사용한 제목·설명 보기</summary>{data.messageRows.map((r,i)=><div className="report-evidence" key={`${r.name}-${i}`}><strong>{r.name}</strong><p>{r.available?r.evidence:'제목·메타 설명을 수집하지 못했습니다.'}</p>{r.url&&<Link url={r.url}>페이지 확인</Link>}</div>)}</details></article>;
}
export function KeywordOpportunities({data}:{data:ReportInsights}) {
 const [selected,setSelected]=useState('');
 const current=data.gaps.find(k=>k.keyword===selected);
 return <article className="report-card" aria-label="키워드 연결 기회"><Heading label="검색 제목에 담을 내용" title="자주 쓰는 말 중, 대표 상품·서비스를 골라 주세요" note="아래는 본문에 자주 나오지만 검색 제목·설명에는 빠진 표현입니다. 빠졌다고 오류는 아닙니다. 실제 주력 상품·서비스를 뜻하는 말만 골라 제목을 검토하세요."/>
 <div className="keyword-simple-guide"><strong>이렇게 사용하세요</strong><ol><li>우리 사업을 설명하는 단어인지 확인합니다.</li><li>맞으면 아래 단어를 선택합니다. 다른 브랜드·메뉴명·일반어라면 건너뛰세요.</li><li>검색 제목 수정안에 자연스럽게 담고, 같은 단어를 반복해 넣지 마세요.</li></ol></div>
 {data.gaps.length?<div className="keyword-choice-list" role="group" aria-label="대표 표현 선택">{data.gaps.map(k=><button type="button" key={k.keyword} aria-pressed={selected===k.keyword} onClick={()=>setSelected(selected===k.keyword?'':k.keyword)}><strong>{k.keyword}</strong><span>본문에서 {k.count}회 사용</span><small>{!k.inTitle?'검색 제목에 없음':''}{!k.inTitle&&!k.inMetaDescription?' · ':''}{!k.inMetaDescription?'검색 설명에 없음':''}</small><b>{selected===k.keyword?'선택됨':'이 표현 검토하기'}</b></button>)}</div>:<Empty>현재 저장된 자료에서 제목·설명을 검토할 표현을 찾지 못했습니다.</Empty>}
 {current&&<div className="keyword-next-step" aria-live="polite"><strong>‘{current.keyword}’이 대표 상품·서비스라면</strong><p>검색 제목은 ‘{current.keyword}의 실제 특징 또는 제공 범위 | 브랜드명’처럼 페이지 내용을 설명하세요. 본문에 없는 약속은 넣지 마세요.</p><ReportJumpLink id="report-page-edits">검색 제목·설명 수정안 열기</ReportJumpLink></div>}
 <p className="report-note">사용 횟수는 이 페이지에서 수집한 글의 빈도입니다. 검색량이나 인기 순위를 뜻하지 않습니다.</p></article>;
}
export function ActionBacklog({data}:{data:ReportInsights}) {
  const [group,setGroup]=useState('전체');const [query,setQuery]=useState('');const [expanded,setExpanded]=useState(false);
  const groups=['전체',...new Set(data.tasks.map(t=>t.group))];const filtered=data.tasks.filter(t=>(group==='전체'||t.group===group)&&`${t.title} ${t.evidence} ${t.action}`.toLowerCase().includes(query.trim().toLowerCase()));const shown=expanded?filtered:filtered.slice(0,6);
  const names={fail:'우선 보완',warning:'보완',review:'내용 검토'};
  return <article className="report-card" aria-label="통합 보완 목록"><Heading label="ACTION BACKLOG" title="놓치지 않고 실행할 보완 목록" note={insightNotes.tasks}/><div className="report-backlog-controls"><label>보완 항목 검색<input type="search" placeholder="예: H1, 이미지, 출처" value={query} onChange={e=>{setQuery(e.target.value);setExpanded(false);}}/></label><p role="status"><strong>{filtered.length}</strong> / {data.tasks.length}개 항목</p></div><div className="report-backlog-distribution" role="group" aria-label="보완 분야 필터">{groups.map(g=>{const count=g==='전체'?data.tasks.length:data.tasks.filter(t=>t.group===g).length;return <button type="button" key={g} aria-pressed={g===group} onClick={()=>{setGroup(g);setExpanded(false);}}><span>{g}</span><strong>{count}<small>개</small></strong><span className="report-meter" aria-hidden="true"><i style={{width:`${data.tasks.length?100*count/data.tasks.length:0}%`}}/></span></button>;})}</div><div className="report-detail-list">{shown.map(t=><details key={t.id}><summary><span className={`report-pill ${t.status==='fail'?'danger':t.status==='warning'?'warning':''}`}>{names[t.status]}</span><span className="report-summary-title">{t.title}</span><span className="report-source-name">{t.group}</span></summary><div className="report-detail-body"><EvidenceFlow items={[{label:'확인 근거',content:t.evidence},{label:'실행할 내용',content:t.action}]}/><p className="report-note">진단 출처: {t.source} · 실제 수정 전 담당자 확인 필요</p><Guidebook title={t.title} scope={t.guideScope} instructions={t.instructions} completion={t.completion} current={t.current} evidence={t.evidence} proposal={t.action}/></div></details>)}</div>{!shown.length&&<Empty>이 조건에 해당하는 보완 항목이 없습니다.</Empty>}{filtered.length>6&&<button type="button" className="report-secondary-button mt-4" onClick={()=>setExpanded(!expanded)}>{expanded?'보완 목록 접기':`전체 ${filtered.length}개 보완 항목 보기`}</button>}</article>;
}
