import type {ExtractedWebsiteData} from './extractWebsite';
import type {NaverCheck,NaverOptimization} from './naverSchema';
import {NAVER_REVIEWED_AT,NAVER_SOURCES} from './naverKnowledge';
import {evaluateRobots,type RobotsObservation} from './robotsRules';

/** Inspect generic/Yeti directives without applying another agent's HTTP directive. */
export function naverDirectives(meta:{agent:string;content:string}[],header:string):Set<string> {
  const directives=meta.filter(m=>['robots','yeti'].includes(m.agent.toLowerCase())).flatMap(m=>m.content.toLowerCase().split(/[\s,]+/));
  let agent='';
  for(const part of header.toLowerCase().split(',')) {
    const scoped=part.trim().match(/^([\w*-]+)\s*:\s*(.*)$/);
    if(scoped){if(['unavailable_after','max-snippet','max-image-preview','max-video-preview'].includes(scoped[1]))continue;agent=scoped[1];}
    if(!agent||agent==='yeti'||agent==='*')directives.push(...(scoped?scoped[2]:part).trim().split(/\s+/));
  }
  return new Set(directives);
}
function robotsFinding(r:RobotsObservation|undefined,agent:'Yeti'|'Ads-Naver',path:string):Pick<NaverCheck,'status'|'evidence'> {
  if(!r)return {status:'manual',evidence:'robots.txt 관측 없음'};
  if(r.status==='missing')return {status:'observed',evidence:`${r.url} · HTTP ${r.httpStatus} · robots 규칙 없음으로 처리되는 응답. 방화벽·실제 봇 접근은 별도 확인`};
  if(r.status!=='ok')return {status:r.httpStatus&&r.httpStatus>=500?'action':'manual',evidence:`robots.txt ${r.httpStatus?`HTTP ${r.httpStatus}`:'응답 확인 불가'} · ${r.status==='non_text'?'HTML 응답으로 규칙을 판정하지 않음':r.status==='too_large'?'검사 범위를 넘는 문서':'규칙 판정 불가'}`};
  const result=evaluateRobots(r.text||'',agent,path);
  return {status:result.allowed===null?'manual':result.allowed?'observed':'action',evidence:`${agent} · ${path} · ${result.rule}${agent==='Ads-Naver'&&!result.explicit?' · 일반 * 그룹 제외':''}`};
}
function types(obj:Record<string,unknown>):string[] {
  return (Array.isArray(obj['@type'])?obj['@type']:[obj['@type']]).filter((v):v is string=>typeof v==='string').map(v=>v.replace(/^https?:\/\/schema.org\//,''));
}
export function analyzeNaverOptimization(data:ExtractedWebsiteData|null,targetUrl=data?.finalUrl||data?.url||''):NaverOptimization {
  const e=data?.seoEvidence;
  const d=e?data:null;
  const mode=d?'diagnosis':'guide';
  let path='/';let origin='해당 사이트';
  try {const u=new URL(targetUrl);path=u.pathname+u.search;origin=u.origin;}catch{}
  const checks:NaverCheck[]=[];
  const add=(c:Omit<NaverCheck,'priority'|'basis'> & Partial<Pick<NaverCheck,'priority'|'basis'>>)=>checks.push({...c,priority:c.priority||'normal',basis:c.basis||'official',...!d?{status:'manual' as const,evidence:'이 보고서에는 새 기준의 원본 관측이 없습니다. 재진단 후 확인하세요.'}:{}});
  const directives=naverDirectives(e?.robotsMeta||[],e?.xRobotsTag||'');
  const noindex=directives.has('noindex')||directives.has('none');
  const robots=e?.robots;
  add({id:'search-robots',title:'Yeti의 대상 경로 수집 규칙',category:'search',owner:'developer',priority:'high',...robotsFinding(robots,'Yeti',path),interpretation:'robots 규칙 판정과 실제 네이버 봇의 접속 성공은 다릅니다. 5xx 응답은 수집 제한 원인이 될 수 있으며 이전 규칙이 사용될 수도 있습니다.',steps:[`${origin}/robots.txt에서 Yeti 전용 그룹과 * 그룹을 구분합니다.`,`${path}와 필요한 JS·CSS 경로의 Allow/Disallow를 확인합니다. 공개할 경로만 수정하고 비공개 경로는 유지합니다.`,'서치어드바이저의 robots 검증 및 서버 접근 로그로 다시 확인합니다.'],completion:'대상 페이지와 필수 리소스의 수집 의도·규칙·실제 접근 결과 대조',sourceIds:['robots','javascript']});
  add({id:'search-index',title:'색인 제외 지시 확인',category:'search',owner:'developer',priority:'high',status:noindex?'action':directives.has('nofollow')?'manual':'observed',evidence:`meta: ${(e?.robotsMeta||[]).map(m=>`${m.agent}=${m.content}`).join(' / ')||'없음'} · X-Robots-Tag: ${e?.xRobotsTag||'없음'}`,interpretation:noindex?'현재 응답에서 네이버에 적용될 수 있는 noindex/none 지시를 발견했습니다. 공개 검색에 노출할 페이지인지 먼저 결정하세요.':'관측한 응답의 색인 제외 지시를 점검했습니다. 제외 지시가 없어도 실제 색인은 보장되지 않습니다.',steps:['해당 URL을 공개 검색에 노출할 의도가 있는지 확인합니다.','노출 대상일 때만 CMS 검색 허용 설정, meta robots, 서버 X-Robots-Tag를 수정합니다. 비공개·관리 페이지에는 적용하지 않습니다.','배포 후 최종 도착 URL의 HTML과 응답 헤더를 다시 확인합니다.'],completion:'공개 의도와 최종 응답의 색인 지시 일치',sourceIds:['structure','missing']});
  add({id:'search-sourceinfo',title:'AI 출처설명 설정의 범위',category:'search',owner:'marketer',status:directives.has('nosourceinfo')?'manual':'observed',evidence:`nosourceinfo ${directives.has('nosourceinfo')?'감지':'미감지'}`,interpretation:'nosourceinfo는 AI가 자동 생성하는 사이트 출처설명을 제어합니다. 모든 AI 학습·인용·브리핑 노출을 일괄 차단하는 설정으로 해석하지 않습니다.',steps:['출처설명을 제공할지 운영 정책을 확인합니다.','설명 제외가 목적일 때 공식 로봇 메타 태그 가이드의 nosourceinfo 적용 범위를 검토합니다.'],completion:'정책 목적과 태그 의미를 담당자가 확인',sourceIds:['structure']});
  const canonicals=e?.canonicals||[];
  const canonicalValid=canonicals.length===1&&/^https?:\/\//i.test(canonicals[0]);
  let sameHost=false;try{sameHost=new URL(canonicals[0]).origin===origin;}catch{}
  add({id:'search-canonical',title:'대표 URL·중복 주소 정리',category:'search',owner:'developer',status:canonicals.length>1||(canonicals.length===1&&!canonicalValid)?'action':canonicalValid&&sameHost?'observed':'manual',evidence:canonicals.length?canonicals.join(' / '):'canonical 태그 미감지',interpretation:'대표 URL은 중복 콘텐츠를 정리하는 신호입니다. 태그 부재만으로 모든 페이지를 오류 처리하지 않으며 다른 도메인 지정도 의도 확인이 필요합니다.',steps:[`현재 주소 ${targetUrl}와 상품 옵션·추적 파라미터 등 중복 주소를 나열합니다.`,'동일 콘텐츠의 대표 절대 URL을 하나로 정하고 canonical·내부 링크·사이트맵을 일치시킵니다.','호스트나 프로토콜 전체를 통합할 때는 서버 리다이렉트를 검토합니다.'],completion:'대표 URL 1개와 중복 주소 처리 정책 대조',sourceIds:['structure']});
  add({id:'search-title',title:'페이지 제목의 존재·중복',category:'search',owner:'content',status:!d?.title||e?.titleCount!==1?'action':'observed',evidence:`title ${e?.titleCount||0}개 · ${d?.title||'비어 있음'}`,interpretation:'정해진 글자 수에 맞추는 진단이 아닙니다. 페이지 주제와 브랜드를 간결하게 설명하고 무관한 인기 키워드·반복을 줄입니다.',steps:['CMS의 이 페이지 SEO 제목 필드를 엽니다.','홈은 브랜드·서비스 정체성, 상세 페이지는 해당 상품·주제를 구체적으로 작성합니다.','페이지 소스에 title이 하나만 출력되고 다른 페이지와 불필요하게 중복되지 않는지 확인합니다.'],completion:'고유하고 정확한 제목 1개 · 검색 결과 제목은 자동 재구성될 수 있음',sourceIds:['metadata','ads-diagnostic']});
  add({id:'search-description',title:'페이지 설명의 존재·중복',category:'search',owner:'content',status:!d?.description||e?.descriptionCount!==1?'action':'observed',evidence:`description ${e?.descriptionCount||0}개 · ${d?.description||'비어 있음'}`,interpretation:'설명은 내용을 1~2문장으로 요약합니다. 40~160자 같은 임의 범위를 네이버 합격 기준으로 사용하지 않습니다.',steps:['페이지에서 실제 제공하는 대상·내용·차이를 1~2문장으로 씁니다.','본문과 모순되거나 전 페이지에 복제된 설명을 바꾸고 소스에서 중복 태그를 제거합니다.'],completion:'설명 1개와 실제 콘텐츠 일치 · 실제 검색 요약문 일치 보장 없음',sourceIds:['metadata']});
  add({id:'search-alt',title:'중요 이미지와 장식 이미지 구분',category:'search',owner:'content',status:!d?.imageCount?'not_applicable':e?.imagesMissingAlt?'action':e?.imagesEmptyAlt?'manual':'observed',evidence:`이미지 ${d?.imageCount||0}개 · alt 속성 누락 ${e?.imagesMissingAlt||0}개 · 빈 alt ${e?.imagesEmptyAlt||0}개`,interpretation:'중요한 정보를 전달하는 이미지에는 대체 설명이 필요합니다. 장식 이미지의 alt=""는 올바른 사용일 수 있으므로 누락과 구분합니다.',steps:['상품·가격·버튼 기능을 전달하는 이미지와 장식 이미지를 나눕니다.','중요 이미지에는 문맥에 맞는 설명을, 장식 이미지에는 빈 alt를 지정합니다.','이미지 속 핵심 안내는 본문에서도 읽을 수 있게 배치합니다.'],completion:'이미지 용도별 대체 텍스트 검토 완료',sourceIds:['alt','ads-diagnostic']});
  add({id:'search-schema',title:'구조화 데이터 문법·형식',category:'search',owner:'developer',status:e?.jsonLdErrors?'action':d?.schemaTypes.length?'observed':'manual',evidence:`JSON-LD 유형: ${[...new Set(d?.schemaTypes||[])].join(', ')||'미감지'} · 파싱 실패 ${e?.jsonLdErrors||0}개 · Microdata ${e?.microdataCount||0}개 · RDFa ${e?.rdfaCount||0}개`,interpretation:'JSON-LD 외의 형식도 존재합니다. 여러 타입 개수로 가점을 주지 않으며 문법 성공은 의미 정확성·검색 반영을 보장하지 않습니다.',steps:['해당 페이지의 실제 콘텐츠 유형을 정합니다. JSON-LD를 쓰면 괄호·따옴표·쉼표 오류부터 고칩니다.','공식 문서에 연결된 구조화 데이터 검증 도구에서 페이지 또는 코드를 검사합니다.','표시되지 않는 가격·별점·후기를 추가하지 말고 화면 내용과 일치시킵니다.'],completion:'문법 검사와 페이지 내용 대조 완료',sourceIds:['structured']});
  add({id:'search-render',title:'렌더링·링크·속도 실제 확인',category:'search',owner:'developer',basis:'observation',status:'manual',evidence:`정적 본문 ${d?.bodyTextLength||0}자 · head 동기 스크립트 ${d?.headSyncScripts.length||0}개 · HTML 수신 ${((d?.responseTimeMs||0)/1000).toFixed(2)}초`,interpretation:'이 시간은 서버에서 HTML을 한 번 수신한 관측이며 TTFB·화면 로딩·Core Web Vitals가 아닙니다. 글자 수나 리소스 개수만으로 수집 실패를 판정하지 않습니다.',steps:['브라우저 화면과 원본 HTML을 비교해 제목·설명·주요 링크가 언제 생성되는지 확인합니다.','독립 콘텐츠를 # 해시만으로 구분한다면 실제 경로 URL을 제공하고 주요 HTML의 서버 렌더링을 검토합니다.','JS·CSS 수집 허용과 모바일 실제 로딩을 측정합니다. 동작 버튼과 페이지 이동 링크를 구분합니다.'],completion:'주요 콘텐츠의 렌더링·개별 URL·필수 리소스 접근 확인',sourceIds:['javascript']});
  add({id:'search-ownership',title:'서치어드바이저 소유확인',category:'search',owner:'marketer',status:'manual',evidence:d?.naverSiteVerification?'소유확인 메타태그 감지 · 계정의 인증 상태는 미확인':'소유확인 메타태그 미감지 · HTML 파일 인증 가능',interpretation:'메타태그와 HTML 파일 방식이 있습니다. 태그 유무로 미연동·인증 성공을 단정하지 않습니다.',steps:[`서치어드바이저에서 ${origin}에 해당하는 호스트를 선택합니다.`,'소유확인 상태와 만료 여부를 계정에서 확인하고 미확인일 때 제공되는 파일 또는 메타태그 방식을 적용합니다.','프로토콜·서브도메인·리다이렉트가 등록한 사이트와 일치하는지 확인합니다.'],completion:'계정 화면의 소유확인 상태·호스트 기록',sourceIds:['ownership']});
  const sitemapLines=(robots?.text||'').split(/\r?\n/).filter(l=>/^\s*sitemap\s*:/i.test(l)).map(l=>l.trim()).slice(0,5);
  add({id:'search-sitemap',title:'사이트맵 제출·발견 경로',category:'search',owner:'developer',status:'manual',evidence:sitemapLines.length?sitemapLines.join(' / '):'robots.txt에서 Sitemap 선언 미확인 · 제출 여부 미확인',interpretation:'파일 선언, 파일 접근, 서치어드바이저 제출은 서로 다른 상태입니다. RSS는 모든 사이트의 필수 항목이 아닙니다.',steps:['CMS에서 생성한 실제 사이트맵 URL을 확인합니다. /sitemap.xml이 반드시 정답인 것은 아닙니다.','소유확인 호스트와 일치하는 공개 URL을 넣고 네이버 제출 제한인 파일 10MB 미만·URL 50,000개 미만을 확인합니다. 필요하면 인덱스로 나눕니다.','서치어드바이저에 제출하고 처리 상태를 기록합니다. lastmod는 실제 수정일에 맞춥니다.'],completion:'유효한 파일·제출 결과 확인 · 색인 성공은 별도 확인',sourceIds:['feed','robots']});
  add({id:'search-og',title:'공유 미리보기·대표 이미지',category:'search',owner:'content',status:d?.ogTitle&&d?.ogDescription&&d?.ogImage?'observed':'manual',evidence:`OG 제목 ${d?.ogTitle?'있음':'미감지'} · 설명 ${d?.ogDescription?'있음':'미감지'} · 이미지 ${d?.ogImage||'미감지'}`,interpretation:'태그 존재만 확인했습니다. 대표 이미지의 실제 크기·파일 용량·내용은 이 검사에서 측정하지 않습니다.',steps:['OG 제목·설명·이미지를 해당 페이지 내용에 맞게 지정합니다.','공식 가이드의 이미지 크기·용량·가로세로 비율 조건을 확인하고 대표 이미지를 직접 열어 검토합니다.','공유 미리보기를 새로 불러와 변경 내용을 확인합니다.'],completion:'실제 공유 미리보기와 대표 콘텐츠 일치',sourceIds:['metadata']});
  add({id:'search-content',title:'고유한 내용·근거·반복 표현',category:'search',owner:'content',status:'manual',evidence:'단어 빈도·연도·외부 링크 수로 전문성이나 AI 인용 확률을 판정하지 않음',interpretation:'중복 키워드를 동의어로 바꾸는 데 그치지 말고, 독자가 필요한 실제 정보와 운영자의 경험을 보완합니다.',steps:['반복 문장이 새 정보를 주는지 확인하고 중복 안내를 합칩니다.','가격의 적용 조건, 서비스 범위, 검증 가능한 사례처럼 해당 URL에서만 답할 수 있는 정보를 추가합니다.','인용 원문을 연결하고 날짜는 내용을 실제 검토·수정한 때만 갱신합니다.'],completion:'중복 제거와 실질 정보 보완 · 사실·인용 원문 검토',sourceIds:['content','briefing']});
  add({id:'search-local',title:'지역 사업자의 플레이스 정보 대조',category:'search',owner:'marketer',basis:'observation',status:'manual',evidence:`상세 플레이스 링크 ${d?.hasNaverPlaceLink?'감지':'미감지'} · 계정 등록·사업 유형 미확인`,interpretation:'오프라인 매장·지역 사업자일 때 적용합니다. 지도 iframe이 없다고 미연동 처리하거나 존재를 확인하지 못한 AI 노출 스위치를 안내하지 않습니다.',steps:['지역 방문이 필요한 사업인지 먼저 확인합니다. 해당하지 않으면 이 항목을 적용하지 않습니다.','해당할 때 홈페이지의 상호·주소·연락처·영업시간을 실제 플레이스 및 운영 정보와 대조합니다.'],completion:'해당 사업의 공개 정보 일치 확인 또는 적용 제외 결정',sourceIds:['content']});
  add({id:'ads-robots',title:'Ads-Naver 전용 수집 규칙',category:'ads',owner:'developer',priority:'high',...robotsFinding(robots,'Ads-Naver',path),interpretation:'광고 크롤러는 Yeti와 다릅니다. 일반 * 그룹만으로 광고 수집 차단을 단정하지 않으며 Ads-Naver를 명시한 제외 규칙을 별도로 봅니다.',steps:['광고 연결 URL의 robots.txt에서 Ads-Naver 전용 규칙을 확인합니다.','의도한 광고 수집 범위를 정한 뒤 규칙을 수정하고 URL 진단도구에서 실제 결과를 확인합니다.','방화벽은 User-Agent 문자열만 믿고 해제하지 말고 공식 봇 확인 방법과 서버 로그를 사용합니다.'],completion:'명시 규칙과 광고 수집진단 결과 대조',sourceIds:['ads-robot','ads-exclusion','ads-diagnostic']});
  add({id:'ads-url',title:'광고 URL의 수집·색인 상태',category:'ads',owner:'marketer',priority:'high',status:'manual',evidence:'광고 계정에 접근하지 않음 · 수집/색인 성공 미확인',interpretation:'URL 진단은 광고 영역의 결과입니다. 서치어드바이저 색인이나 자연 검색 순위와 동일하지 않습니다.',steps:['파워링크 광고그룹의 열맞춤설정에서 연결URL 수집 상태를 추가하고 상세 결과를 엽니다.','결과 없음이면 광고 ON/OFF·기간·잔액·소재/키워드·비즈채널 상태를 먼저 확인합니다.','전일 수집/당일 오전 색인 기준과 진단 요청 시각을 기록합니다. 수정 후 현황진단 결과를 다시 확인합니다.'],completion:'동일 연결 URL의 수집·색인 결과와 확인 시각 기록 · 정상이어도 노출 보장 없음',sourceIds:['ads-status']});
  add({id:'ads-size',title:'광고 크롤러용 HTML 크기·형식',category:'ads',owner:'developer',status:d?.contentTypeOk&&(d?.pageSizeBytes||0)<=4*1024*1024?'observed':'action',evidence:`HTML ${((d?.pageSizeBytes||0)/1024/1024).toFixed(2)} MiB · HTML Content-Type ${d?.contentTypeOk?'확인':'미확인'}`,interpretation:'4MB 관련 안내는 Ads-Naver URL 진단에 해당합니다. HTML 바이트 관측이며 이미지·JS를 포함한 전체 페이지 용량이나 자연 검색 합격선이 아닙니다.',steps:['대용량 인라인 데이터·base64·불필요한 HTML 중복을 점검합니다.','광고 랜딩의 응답 형식을 확인하고 최적화 후 URL 수집진단을 다시 실행합니다.'],completion:'HTML 원문 크기·형식 재확인 및 광고 진단 결과 대조',sourceIds:['ads-diagnostic']});
  add({id:'ads-redirect',title:'광고 연결 URL의 이동 경로',category:'ads',owner:'developer',status:d?.selfRedirect||(d?.redirectChain.length||0)>=5?'action':'observed',evidence:`리다이렉트 ${d?.redirectChain.length||0}회 · 최종 주소 ${targetUrl}`,interpretation:'공식 광고 URL 진단은 과도한 리다이렉트와 순환을 점검합니다. 한 번의 정상 이동을 오류로 간주하지 않습니다.',steps:['광고에 등록한 주소와 최종 랜딩 주소를 비교합니다.','필요한 추적·언어 설정을 유지하면서 불필요한 우회를 줄이고 순환을 제거합니다.','오류 안내 문구가 있어도 실제 오류 화면인지 확인한 뒤 HTTP 상태를 정정합니다.'],completion:'광고 클릭 목적을 유지한 정상 도착과 실제 HTTP 상태 확인',sourceIds:['ads-diagnostic']});
  add({id:'ads-ai',title:'AI 광고·확장검색 적용 범위',category:'ads',owner:'marketer',status:'manual',evidence:'광고그룹 유형·AI 광고 설정·심사 상태 미확인',interpretation:'AI 브리핑 내 AI 광고와 자연 검색의 AI 출처 인용은 별개입니다. 2026년 6월 출시 공지의 대상은 ADVoost 검색이며 현재 계정의 제공 범위를 확인해야 합니다.',steps:['광고주센터의 최신 공지와 해당 광고그룹에서 AI 광고 지원 여부·심사 제한을 확인합니다.','AI 광고 및 확장검색 설정, 예산 배분을 담당자가 검토합니다. 스캐너가 예산이나 광고를 변경하지는 않습니다.','노출 소재와 연결 URL이 실제 서비스·조건을 정확히 표현하는지 확인합니다.'],completion:'계정의 지원 범위·설정·심사 상태 기록',sourceIds:['ai-ad','briefing']});
  const products=(d?.jsonLdSchemas||[]).filter(obj=>types(obj).includes('Product'));
  const completeProducts=products.filter(obj=>typeof obj.name==='string'&&obj.name.trim()&&typeof obj.description==='string'&&obj.description.trim());
  add({id:'ads-schema',title:'상품·사업 정보의 같은 항목 내 일치',category:'ads',owner:'developer',status:products.length&&completeProducts.length!==products.length?'action':'manual',evidence:`Product ${products.length}개 · 같은 Product 안에 name+description ${completeProducts.length}개`,interpretation:'다른 객체의 name과 description을 합쳐 완성으로 판정하지 않습니다. 상품이면 Product, 지역 사업이면 해당 사업 유형을 검토하고 가격·평점은 실제 자료가 있을 때만 작성합니다.',steps:['현재 URL이 상품 상세·지역 사업·다른 콘텐츠 중 무엇인지 확인합니다.','실제 대상 객체에 이름·설명과 해당하는 정보를 넣고 화면의 상품·사업 정보와 대조합니다.','가격은 실제 판매 조건으로, aggregateRating은 실제 집계가 있을 때만 작성합니다. 임의 후기를 생성하지 않습니다.'],completion:'콘텐츠 유형·동일 객체 필드·보이는 정보의 일치 및 구조화 데이터 검증',sourceIds:['ai-ad','structured']});
  add({id:'ads-name',title:'광고 계정의 비즈채널 이름',category:'ads',owner:'marketer',status:'manual',evidence:`페이지 og:site_name: ${d?.ogSiteName||'미감지'} · 계정 비즈채널 이름 미확인`,interpretation:'페이지의 OG 이름과 광고 계정의 비즈채널 이름은 다릅니다. 영문 브랜드명이라는 이유로 감점하지 않습니다.',steps:['광고 계정에서 등록한 웹사이트 비즈채널 이름을 확인합니다.','실제 브랜드·서비스를 구체적으로 나타내는지 확인하고 랜딩의 표기와 대조합니다.'],completion:'계정에 등록된 이름과 실제 브랜드 표기 확인',sourceIds:['ai-ad']});
  add({id:'ads-conversion',title:'전환 추적 신호와 이벤트 수신',category:'ads',owner:'developer',status:'manual',evidence:d?.hasNaverConversionScript?'HTML에서 네이버 전환 스크립트 호출 신호 감지 · 실행/수신 미확인':`HTML에서 네이버 전환 신호 미감지${d?.hasGTM?' · GTM 감지(런타임 설치 여부 미확인)':''}`,interpretation:'스크립트 문자열·GTM·GA 존재로 네이버 전환 연동 성공을 판정하지 않습니다. 동의 설정과 런타임 설치 때문에 정적 HTML에서 보이지 않을 수도 있습니다.',steps:['계정이 제공하는 해당 광고 상품의 설치 가이드를 기준으로 전환 목표·도메인·태그 설정을 확인합니다.','동의 정책을 지킨 테스트 환경에서 문의·구매 등 목표 행동을 실행합니다.','브라우저 요청과 광고 계정 수신 내역을 대조하고 중복 발화·구매 금액·통화를 확인합니다.'],completion:'테스트 행동과 이벤트 수신의 대조 기록 · 정상 수신 전에는 연동 성공으로 표시하지 않음',sourceIds:['ai-ad','shopping']});
  add({id:'ads-mobile',title:'모바일 랜딩의 실제 이용 흐름',category:'ads',owner:'developer',basis:'observation',status:'manual',evidence:`viewport: ${d?.viewportMeta||'미감지'}`,interpretation:'viewport는 반응형 설정의 단서입니다. 실제 화면·폼·결제 동작을 확인하지 않고 모바일 최적화 완료를 판정하지 않습니다.',steps:['작은 모바일 화면에서 광고 랜딩을 열어 가로 넘침과 글자·버튼 크기를 확인합니다.','문의 또는 구매를 직접 진행해 키보드·입력 오류·동의·완료 화면을 점검합니다.'],completion:'PC·모바일의 목표 행동 완료 기록',sourceIds:['ads-diagnostic']});
  add({id:'shopping-feed',title:'쇼핑 상품 연동·광고 적격성',category:'shopping',owner:'marketer',status:'manual',evidence:'네이버쇼핑 입점·상품 피드·광고 계정 상태 미확인',interpretation:'쇼핑몰 사업자에게 적용됩니다. ADVoost 쇼핑은 검색광고 랜딩 SEO와 별도로 상품 연동과 운영 조건을 확인해야 합니다.',steps:['네이버쇼핑 상품 연동 및 광고 계정의 상품 사용 가능 상태를 확인합니다.','캠페인·애셋그룹·상품 목록과 제외·심사 사유를 확인합니다. 쇼핑몰이 아니면 적용하지 않습니다.'],completion:'실제 광고 가능 상품과 계정 상태 확인',sourceIds:['shopping']});
  add({id:'shopping-tracking',title:'스마트스토어·외부몰 전환 구분',category:'shopping',owner:'developer',status:'manual',evidence:'판매 채널·자동 적용 여부·전환 수신 미확인',interpretation:'스마트스토어 비즈채널과 외부몰은 전환 설정 절차가 다를 수 있습니다. 모든 몰에 수동 wcs 설치를 일괄 권하지 않습니다.',steps:['광고 비즈채널이 스마트스토어인지 외부몰인지 확인합니다.','스마트스토어는 채널 등록 후 자동 적용 상태를, 외부몰은 등록·설치·전환 목표를 공식 안내와 대조합니다.','테스트 주문이 실제 집계되는지와 중복 설치 여부를 확인합니다.'],completion:'해당 채널의 설치 방식과 구매 전환 수신 확인',sourceIds:['shopping']});
  add({id:'shopping-consistency',title:'상품 피드와 랜딩의 정보 대조',category:'shopping',owner:'content',basis:'observation',status:'manual',evidence:'피드를 가져오지 않았으므로 가격·재고·옵션 일치 여부 미확인',interpretation:'스캐너가 권하는 운영 점검입니다. 공개 HTML의 가격 숫자만으로 광고 상품 연동을 검증할 수 없습니다.',steps:['광고 대상 상품 하나를 골라 상품 ID·옵션·판매 가격·재고·도착 URL을 나란히 확인합니다.','피드·쇼핑 채널·상세 페이지 중 정보가 늦게 갱신되는 지점을 수정합니다.'],completion:'같은 상품·옵션의 실제 판매 정보 대조 기록',sourceIds:['shopping']});
  add({id:'developers-observation',title:'검색 API 응답과 실제 검색 화면 구분',category:'developers',owner:'marketer',status:'manual',evidence:'별도 웹문서 API 관측 카드의 정상·실패 상태를 확인하세요.',interpretation:'웹문서 API 응답 순서를 네이버 통합검색 순위로 표시하지 않습니다. 이번 응답에서 찾지 못해도 사이트 전체 미노출이나 유입 부재를 뜻하지 않습니다.',steps:['관측 시각·검색어·요청 범위·정상 응답 여부를 확인합니다.','응답 내 위치, API total, 반환 문서 수를 구분합니다. 오류·시간 초과는 미발견 통계에서 제외합니다.','실제 검색 화면·서치어드바이저 데이터는 별도로 대조합니다.'],completion:'동일 검색어의 API 관측 조건·제한 기록',sourceIds:['search-api']});
  add({id:'developers-credentials',title:'API 권한·호출 한도·키 관리',category:'developers',owner:'developer',status:'manual',evidence:'진단 대상 사이트의 개발자 계정·키 설정은 읽지 않음',interpretation:'검색 API는 비로그인 방식이며 서버에서 Client ID·Secret을 사용합니다. API 호출 성공은 대상 사이트의 소유확인이나 광고 계정 연동 성공이 아닙니다.',steps:['네이버 Developers 애플리케이션의 검색 API 사용 설정과 호출 현황을 확인합니다.','키는 서버 환경변수로 보관하고 클라이언트 번들·공유 보고서·로그에 노출하지 않습니다.','현재 공식 문서의 일일 25,000회 한도와 오류 코드를 확인하고 한도·인증·시간 초과를 분리해 처리합니다.'],completion:'권한·서버 키 관리·사용량·오류 분류 확인',sourceIds:['search-api']});
  add({id:'developers-crawl',title:'수집 요청 API 이용 자격',category:'developers',owner:'developer',status:'manual',evidence:'제휴 사용자용 accessToken·이용 자격 미확인',interpretation:'수집 요청 API는 모든 사이트가 바로 사용할 수 있는 일반 색인 보장 API가 아닙니다. 현재 공식 가이드는 제휴 사용자 대상 발급을 안내합니다.',steps:['서치어드바이저와 공식 가이드에서 API 이용 대상·토큰 발급 가능 여부를 확인합니다.','이용 대상이 아니면 웹마스터도구의 수집 요청·사이트맵 제출 흐름을 사용합니다.','요청 수락과 실제 수집·색인 완료를 분리해 기록합니다.'],completion:'이용 자격 또는 대체 제출 방식 확인',sourceIds:['crawl-api','feed']});
  return {version:2,rulesReviewedAt:NAVER_REVIEWED_AT,observedAt:d?e?.capturedAt:undefined,targetUrl,mode,checks,sources:NAVER_SOURCES};
}
