import type {MarketingReport,PageEvidence} from './reportSchema';
import {safeHttpUrl} from './citationMeasurement';
import {GROWTH_SOURCES,GROWTH_REVIEWED_AT,GROWTH_SCOPE,type GrowthSourceId} from './growthKnowledge';

export type GrowthArea='SEO'|'GEO'|'AEO';
export type GrowthAction={id:string;title:string;areas:GrowthArea[];channel:string;status:'action'|'observed'|'manual';priority:'high'|'normal';owner:string;evidence:string;location:string;steps:string[];toBe:string;change:string;kpi:string;verify:string;sources:GrowthSourceId[]};
export const GROWTH_STATUS={action:'우선 보완 검토',observed:'신호 확인 · 유지 점검',manual:'담당자 확인'};
function sameUrl(a:string,b:string) {try{const x=new URL(a),y=new URL(b);x.hash='';y.hash='';return x.href===y.href;}catch{return false;}}
export function growthPageEvidence(report:MarketingReport):PageEvidence|undefined {
  const p=report.pageEvidence;
  return p&&safeHttpUrl(p.requestedUrl)&&safeHttpUrl(p.finalUrl)&&sameUrl(p.requestedUrl,report.url)?p:undefined;
}
export function buildGrowthPlan(report:MarketingReport) {
  const p=growthPageEvidence(report),s=p?.searchSignals,url=safeHttpUrl(p?.finalUrl||report.url),target=url||'원본 페이지';
  const site=report.meta?.siteName||report.meta?.domain||'우리 사이트';
  const tasks:GrowthAction[]=[];
  const add=(item:GrowthAction)=>tasks.push(item);
  const google=s?.crawlers.find(c=>c.agent==='Googlebot'),naver=s?.crawlers.find(c=>c.agent==='Yeti'),openai=s?.crawlers.find(c=>c.agent==='OAI-SearchBot');
  const noEvidence='이 보고서에는 이 항목의 원본 기술 관측이 없습니다. 재진단하거나 관리 도구에서 확인하세요.';
  add({id:'google-crawl',title:'Google이 이 페이지를 읽을 수 있는지 확인',areas:['SEO','GEO'],channel:'Google',status:google?.allowed===false?'action':google?.allowed===true?'observed':'manual',priority:'high',owner:'개발 담당',evidence:google?.detail||noEvidence,
    location:`${target} · robots.txt · 서버/CDN 설정`,steps:['먼저 검색에 공개할 페이지인지 결정합니다. 회원·관리·개인정보 페이지는 공개 대상으로 바꾸지 않습니다.','Googlebot에 적용되는 그룹에서 해당 경로와 필요한 JS·CSS가 차단됐는지 확인합니다. 공개 의도와 다른 차단만 수정합니다.','Search Console URL 검사에서 최종 URL의 실제 테스트·렌더링을 확인하고, 서버 로그에서 Googlebot 접근을 대조합니다.'],
    toBe:'공개할 페이지의 제목·본문·필수 리소스를 검색로봇이 확인할 수 있는 상태',change:'읽기 장벽을 줄여 수집·색인 검토가 가능한 기반을 만듭니다. robots 규칙 통과는 실제 접속·색인 성공과 다릅니다.',kpi:'URL 검사 상태 · 색인된 대상 URL 수 · 이후 검색 노출',verify:'정적 재진단 + URL 실제 테스트 + 색인 여부를 각각 기록',sources:['ai','robots']});
  const directives=s?.googleDirectives||[],tokens=directives.join(',');
  const excluded=/(?:^|[\s,])(noindex|none|nosnippet)(?:$|[\s,])/.test(tokens)||/(?:^|[\s,])max-snippet:0(?:$|[\s,])/.test(tokens);
  add({id:'google-snippet',title:'색인·답변 미리보기 제외 설정 점검',areas:['SEO','GEO','AEO'],channel:'Google',status:!s?'manual':excluded?'action':'observed',priority:'high',owner:'개발 담당',evidence:s?`Google에 적용되는 수집 응답 지시: ${directives.join(' / ')||'head 메타·응답 헤더에서 제외 지시 미감지'}`:noEvidence,
    location:'CMS 검색 허용 설정 · head의 robots/googlebot 메타 · X-Robots-Tag',steps:['해당 URL을 검색과 AI 답변에서 활용하게 할지 운영 정책을 확인합니다.','공개 대상이라면 noindex·none과 nosnippet·max-snippet:0의 목적을 구분하여 불필요한 설정만 제거합니다. 다른 봇에만 적용되는 지시는 혼동하지 않습니다.','HTML·HTTP 헤더를 함께 확인한 뒤 재수집을 요청합니다. 기존 색인 상태와 변경 반영은 Search Console에서 확인합니다.'],toBe:'공개 의도와 색인·미리보기 지시가 일치하는 페이지',change:'내용이 검색 결과와 답변에 활용되는 것을 제한하던 조건을 검토할 수 있습니다. noindex 제거만으로 색인이 보장되지는 않습니다.',kpi:'색인 제외 사유 · 스니펫 표시 · Google AI 링크 노출',verify:'최종 응답의 지시 재확인 + 관리 도구의 재수집 결과',sources:['robots','control']});
  add({id:'naver-crawl',title:'네이버 수집부터 노출까지 단계별 확인',areas:['SEO','GEO'],channel:'네이버',status:naver?.allowed===false?'action':naver?.allowed===true?'observed':'manual',priority:'high',owner:'개발·마케팅 담당',evidence:naver?.detail||noEvidence,
    location:'서치어드바이저 · robots.txt · 입력 URL의 렌더링',steps:[`서치어드바이저에서 ${target}의 사이트 소유확인·수집·색인 상태를 확인합니다. 메타태그가 없다는 사실만으로 소유확인 실패를 단정하지 않습니다.`,'Yeti의 경로 접근과 JavaScript/CSS 수집을 확인합니다. SPA도 수집을 지원하므로 실제 렌더 결과를 보고 필요하면 주요 콘텐츠의 서버 렌더링을 보완합니다.','사이트맵에는 실제 대표 URL을 넣습니다. 수집 요청 API는 제휴·소유확인·별도 토큰 조건을 먼저 확인하고, 일반 검색 API와 구분합니다.'],toBe:'수집 요청·색인 확인·실제 노출을 구분하여 운영하는 사이트',change:'수집 요청 성공을 노출 성공으로 오해하지 않고 막힌 단계를 찾아 수정합니다.',kpi:'수집·색인 상태 → 웹 검색 노출·클릭·CTR',verify:'디벨로퍼스 웹문서 응답 순서는 관측 참고값으로만 사용 · 실제 실적은 서치어드바이저에서 확인',sources:['naverJs','naverCrawl','naverApi','naverPerformance']});
  add({id:'title-heading',title:'검색 제목과 첫 화면의 약속 맞추기',areas:['SEO','AEO'],channel:'Google · 네이버',status:!p?'manual':!p.title||!p.h1.length?'action':'manual',priority:!p?.title||!p?.h1.length?'high':'normal',owner:'콘텐츠 담당',evidence:p?`현재 title: ${p.title||'미감지'}\n현재 H1: ${p.h1.join(' / ')||'정적 HTML에서 미감지'}\n현재 설명: ${p.description||'미감지'}`:noEvidence,
    location:`${target}의 SEO 제목·설명 입력란과 첫 화면 대표 제목`,steps:['현재 페이지가 해결하는 고객의 질문 하나와 실제 제공 서비스 하나를 정합니다.','검색 제목에는 구체적인 주제와 브랜드를, 대표 제목에는 고객이 얻는 내용을 넣습니다. 대표 제목이 시각적으로 가장 분명한지 확인합니다.','본문에 없는 성과·최상급 표현을 넣지 말고 설명과 본문 내용을 맞춥니다. 글자 수나 H1 개수만으로 순위 효과를 단정하지 않습니다.','배포 후 같은 페이지·검색어·기기 조건의 CTR을 이전 기간과 비교합니다. 검색엔진이 제목·요약을 다시 작성할 수 있습니다.'],toBe:`제목 작성 틀: [실제 서비스·주제] | ${site}\n첫 화면: [어떤 고객]의 [문제]를 [실제 제공 방식]으로 돕습니다.\n설명: [범위·차별점]과 [다음 행동]을 사실에 맞게 설명합니다.`,change:'검색에서 기대한 내용과 방문 후 보이는 내용이 이어져 선택·이해의 혼선을 줄이는 것을 목표로 합니다.',kpi:'해당 URL·검색어 CTR · 방문 후 문의 완료 세션 비율',verify:'제목·본문 일치 확인 → 동일 조건의 노출·클릭 비교',sources:['title','naverContent']});
  add({id:'canonical-links',title:'대표 URL과 내부 링크 연결 정돈',areas:['SEO','GEO'],channel:'Google · 네이버',status:s&&s.canonicals.length>1?'action':'manual',priority:'normal',owner:'개발 담당',evidence:s?`canonical: ${s.canonicals.join(' / ')||'미감지'} · 내부 링크 ${s.internalLinkCount}개`:noEvidence,
    location:'중복 URL · canonical · 메뉴와 본문 링크 · 사이트맵',steps:['추적 파라미터·www·http/https·상품 옵션 등 같은 내용의 URL을 목록으로 만듭니다.','실제 대표 URL을 결정하고 canonical·내부 링크·사이트맵이 충돌하지 않게 정리합니다. 서로 다른 내용을 무조건 홈으로 통합하지 않습니다.','질문 답변·서비스·사례 페이지를 의미 있는 링크 문구로 연결합니다. 독립 콘텐츠를 # 해시 주소에만 의존시키지 않습니다.'],toBe:'고객 질문 → 관련 답변·서비스 → 근거 사례 → 문의의 연결 경로',change:'검색로봇과 방문자가 같은 대표 페이지를 찾고 다음 내용을 탐색하기 쉬워집니다.',kpi:'선택된 대표 URL · 중복 색인 사유 · 관련 페이지 이동과 문의 세션',verify:'대표 URL을 Google URL 검사로 대조하고 실제 링크 경로를 클릭 점검',sources:['canonical','naverJs']});
  const question=report.llmCitationTest?.results.find(r=>!r.branded)?.question||report.llmCitationTest?.results[0]?.question||'이 서비스는 누구에게 적합하며, 어떻게 진행하나요?';
  add({id:'answer-content',title:'질문 하나에 답·조건·근거·다음 행동 연결',areas:['AEO','GEO','SEO'],channel:'답변형 검색 · AI',status:'manual',priority:'normal',owner:'콘텐츠 담당',evidence:`검토할 고객 질문: ${question}\n${p?`저장된 H2: ${p.h2.join(' / ')||'미감지'}`:'문답 존재·정확성은 원문 검토가 필요합니다.'}`,
    location:`${target} 또는 이 질문을 가장 잘 해결하는 별도 상세 페이지`,steps:['질문을 제목으로 놓고 그 바로 아래에 고객에게 필요한 답부터 작성합니다. 짧은 답 뒤에 자세한 설명을 유지합니다.','가격·기간·대상·제외 범위·진행 절차를 확인된 사실로 보완합니다. 답변 길이를 특정 글자 수에 억지로 맞추지 않습니다.','직접 수행한 사례·자료·담당자·확인 날짜를 붙입니다. 비슷한 질문마다 내용이 거의 같은 페이지를 대량 생성하지 않습니다.','질문의 다음 행동에 맞춰 관련 사례 또는 문의 페이지를 연결하고 같은 질문으로 답변·출처를 다시 관측합니다.'],
    toBe:`질문: ${question}\n직접 답변: [확인된 답]\n적용 조건: [대상·범위·예외]\n근거: [직접 경험·자료·출처·확인일]\n다음 행동: [상세 정보 또는 문의 링크]`,change:'고객이 답을 찾고 판단할 수 있는 페이지가 됩니다. 추천 스니펫·AI 답변 선택은 엔진이 결정합니다.',kpi:'동일 질문의 답변·자사 출처 관측 · 해당 페이지 전환 세션',verify:'담당자 사실 검수 → 실제 페이지에서 답변 확인 → 질문·모델·조건 고정 재측정',sources:['snippet','ai','naverBriefing']});
  add({id:'first-party-proof',title:'직접 경험과 검증 가능한 근거 보강',areas:['SEO','GEO','AEO'],channel:'공통',status:'manual',priority:'normal',owner:'콘텐츠·서비스 담당',evidence:p?`본문 ${p.bodyText.length.toLocaleString('ko-KR')}자 저장${p.bodyTruncated?' · 일부 발췌':''}. 이 수치는 전문성·사실 정확도 판정이 아닙니다.`:'저장된 원문만으로 경험·전문성·정확성을 검증할 수 없습니다.',
    location:'사례·서비스 설명 · 작성/검토자 · 회사/연락처 · 출처 링크',steps:['직접 수행한 사례에서 문제·선택한 방법·확인 가능한 결과를 정리합니다. 고객 동의와 공개 가능한 범위를 확인합니다.','외부 자료는 원출처와 기준 날짜를 연결하고, 가격·규정·일정은 실제 변경이 있을 때 갱신합니다.','작성/검토 담당자의 역할과 서비스 제공 주체를 구체적으로 표시합니다. 없는 자격·리뷰·성과를 만들어 넣지 않습니다.'],toBe:'[실제 상황] → [담당자의 판단과 수행] → [확인 가능한 결과·한계] → [근거와 검토일]',change:'다른 사이트의 요약과 구분되는 실제 정보가 쌓이고, 고객과 AI 답변 이용자가 근거를 확인할 수 있습니다.',kpi:'근거 있는 핵심 주장 점검 완료율 · 유효 문의의 질 · 출처 인용 관측',verify:'핵심 주장마다 증빙·담당자·검토일 대조 · 단순 날짜 변경은 개선으로 기록하지 않음',sources:['ai','schema']});
  add({id:'structured-data',title:'실제 콘텐츠에 맞는 구조화 데이터 검증',areas:['SEO','GEO'],channel:'Google · 네이버',status:s?.jsonLdErrors?'action':'manual',priority:'normal',owner:'개발·콘텐츠 담당',evidence:s?`JSON-LD 유형: ${s.schemaTypes.join(', ')||'미감지'} · 파싱 오류 ${s.jsonLdErrors}개. 다른 마크업 형식·실제 내용은 별도 검토.`:noEvidence,
    location:'페이지 템플릿의 구조화 데이터와 화면에 보이는 상품·사업·문서 정보',steps:['해당 페이지의 콘텐츠 유형과 현재 지원되는 검색 기능을 먼저 확인합니다. 유형 개수를 늘리는 것을 목표로 삼지 않습니다.','오류가 있다면 문법을 수정하고 필수 속성을 실제 화면의 정보로 채웁니다. 다른 객체의 필드를 합쳐 완성으로 처리하지 않습니다.','Google Rich Results Test와 해당 플랫폼 가이드로 검증합니다. 유효한 코드라도 검색 노출은 보장되지 않습니다.','FAQPage를 추가하면 Google FAQ 리치 결과가 나온다는 기존 제안은 제외합니다. 유용한 문답 본문은 유지합니다.'],toBe:'실제 서비스·상품·문서 내용과 일치하는 구조화 데이터',change:'지원되는 검색 표현의 검토 조건을 갖춥니다. 구조화 데이터는 Google AI 검색의 별도 필수 스키마가 아닙니다.',kpi:'지원 유형의 유효 항목 · 오류 수 · 해당 검색 표현 실적',verify:'문법 검증 + 공개 내용 일치 + 현재 지원 기능 확인',sources:['schema','updates','ai']});
  add({id:'google-ai-control',title:'Google AI 검색 참여 설정 확인',areas:['GEO'],channel:'Google AI',status:'manual',priority:'normal',owner:'사이트 소유자',evidence:'공개 HTML로는 Search Console의 계정 설정을 확인할 수 없습니다.',location:'Search Console → 설정 → Search generative AI',steps:['소유확인된 해당 속성에서 참여 설정을 확인합니다.','상위 속성의 설정을 상속하는지 확인하고, 콘텐츠 활용 정책과 원하는 노출 범위를 검토합니다.','참여를 원하는 경우 담당자가 설정을 결정합니다. 스캐너는 이 설정을 자동으로 변경하거나 참여 성공을 판정하지 않습니다.'],toBe:'검색 AI 참여 정책과 실제 속성 설정의 일치',change:'정책상 제외돼 있던 사이트라면 담당자의 결정 후 AI 검색 활용 자격을 검토할 수 있습니다.',kpi:'참여 설정 상태 · 생성형 AI 리포트의 링크 노출',verify:'속성·상속 상태를 기록하고 실제 AI 성과는 별도 확인',sources:['control','aiReport']});
  add({id:'openai-crawl',title:'ChatGPT 검색 봇과 학습 봇 구분',areas:['GEO'],channel:'OpenAI',status:openai?.allowed===false?'action':openai?.allowed===true?'observed':'manual',priority:'normal',owner:'개발·정책 담당',evidence:openai?.detail||noEvidence,location:'robots.txt의 OAI-SearchBot 그룹 · 서버/CDN 접근 로그',steps:['ChatGPT 검색에 콘텐츠를 제공할지 정책을 결정하고 OAI-SearchBot 규칙을 확인합니다.','GPTBot의 학습 이용 설정과 별도로 관리합니다. 검색에 참여하기 위해 학습 봇을 일괄 허용하지 않습니다.','의도한 경로·리소스와 실제 접근을 점검한 뒤 동일한 질문으로 자사 출처 링크를 다시 관측합니다.'],toBe:'검색 참여와 학습 이용 의사를 각각 반영한 봇 정책',change:'서로 다른 사용 목적을 구분하면서 검색 접근 장벽을 확인할 수 있습니다.',kpi:'OAI-SearchBot 접근 로그 · 유효 응답 중 자사 출처 · AI 유입 세션',verify:'규칙 관측·실제 접근·답변 인용을 각각 확인',sources:['openai']});
  add({id:'mobile-performance',title:'모바일 읽기·반응·안정성 실제 측정',areas:['SEO'],channel:'Google · 방문 경험',status:'manual',priority:'normal',owner:'개발·디자인 담당',evidence:s?`정적 HTML ${s.bodyTextLength}자 · JS 의존 의심 신호 ${s.isJsHeavy?'있음':'없음'}. 실제 사용자 성능은 측정하지 않았습니다.`:'이 진단에는 실제 사용자 Core Web Vitals 데이터가 없습니다.',location:'핵심 유입 URL · PageSpeed Insights · Search Console Core Web Vitals',steps:['핵심 유입 페이지를 모바일로 열어 제목·본문·버튼·폼의 사용성을 확인합니다.','실사용자 데이터에서 LCP 2.5초 이하, INP 200ms 이하, CLS 0.1 이하를 75번째 백분위 기준으로 점검합니다. 데이터가 없으면 실험실 결과와 구분합니다.','느린 대표 이미지·상호작용을 막는 스크립트·레이아웃 이동의 실제 원인부터 수정합니다.','폼 완료와 실제 이벤트 수신까지 테스트합니다. 서버 응답 시간이나 viewport 태그만으로 성능을 통과 처리하지 않습니다.'],toBe:'핵심 내용을 읽고 버튼과 문의 폼을 무리 없이 사용할 수 있는 모바일 페이지',change:'대기·오작동·화면 이동에 의한 사용 불편을 줄이는 것을 목표로 합니다.',kpi:'실사용자 LCP·INP·CLS · 모바일 전환 세션 비율',verify:'실사용자/실험실 구분 + 전후 동일 URL·기기 비교 · 상위 노출 보장 아님',sources:['cwv','vitals','analytics']});
  add({id:'measurement',title:'검색·AI·문의 성과의 기준선 만들기',areas:['SEO','GEO','AEO'],channel:'Google · 네이버 · GA4',status:'manual',priority:'high',owner:'마케팅 담당',evidence:'이 스캐너에는 사이트 소유자의 검색 노출·클릭·전환 계정 실적이 연결되어 있지 않습니다.',location:'Search Console · 서치어드바이저 · GA4 · 변경 기록',steps:['가장 중요한 전환 하나(예: 문의 제출 완료)를 정하고 테스트로 실제 수신을 확인합니다.','수정 전 날짜·URL·채널·검색어·기기 조건을 저장합니다. 기본 운영안은 28일 기준선과 변경 후 같은 길이의 기간 비교입니다. 효과 반영 기한을 뜻하지 않습니다.','Google AI 리포트는 제공 여부와 노출량 조건을 확인합니다. 네이버는 업데이트 기준일과 웹 검색 영역 범위를 맞춥니다.','한 번에 바꾸는 핵심 가설을 정하고 클릭·세션·전환을 각 도구의 정의로 기록합니다. 계절성·광고·캠페인 변화를 함께 메모합니다.'],toBe:'변경 내용 → 측정 조건 → 전후 수치 → 유지/수정 판단의 기록',change:'좋아진 부분과 아직 확인되지 않은 부분을 구분해 다음 실행을 결정할 수 있습니다.',kpi:'노출 · CTR · 세션 · 전환 세션 비율 · AI 노출/표본 인용',verify:'계정 원자료와 목표값을 분리 · 단순 전후 차이를 인과 효과로 단정하지 않음',sources:['naverPerformance','aiReport','analytics']});
  add({id:'local-commerce',title:'상품·지역 사업 정보의 실제 일치 확인',areas:['SEO','GEO'],channel:'Google · 네이버',status:'manual',priority:'normal',owner:'서비스·마케팅 담당',evidence:`사이트 유형 참고: ${report.discoverability?.siteType||'미분류'}. 상품 판매·지역 방문 사업에 해당할 때 적용합니다.`,location:'상품 상세·회사 정보 · 해당 사업의 Merchant Center/Business Profile·네이버 상품/플레이스 정보',steps:['상품 판매 또는 지역 방문 서비스에 해당하는지 먼저 확인하고 맞지 않는 등록·마크업은 생략합니다.','상품명·가격·재고·배송·반품 조건 또는 상호·주소·연락처·영업시간을 실제 정보와 맞춥니다.','사이트와 각 관리 채널의 정보를 대조하고 사실 변경이 생길 때 함께 갱신합니다. 허위 리뷰·지역명 반복을 만들지 않습니다.'],toBe:'사이트와 공식 관리 채널에서 같은 상품·사업 정보를 확인할 수 있는 상태',change:'고객이 정보를 재확인하며 겪는 혼선을 줄이고 해당 검색 경험의 정확한 정보 기반을 갖춥니다.',kpi:'정보 불일치 수정 수 · 해당 채널 실적 · 문의/구매 세션',verify:'적용 대상 여부와 계정 소유권부터 확인 · 일반 웹 성과와 분리',sources:['ai','schema']});
  add({id:'ads-organic',title:'자연 검색·AI 출처와 광고 노출을 분리',areas:['SEO','GEO'],channel:'네이버 광고 · 해당 시',status:'manual',priority:'normal',owner:'광고 운영 담당',evidence:'광고 계정 상태·잔액·심사·전환 수신은 이 페이지 진단으로 확인하지 않았습니다. 광고를 집행하는 경우에만 진행합니다.',location:'네이버 광고주센터 → 광고그룹 → 연결URL 수집 상태 · 전환 보고서',steps:['자연 검색의 Yeti와 광고용 Ads-Naver의 수집 상태를 구분합니다. 광고그룹의 연결URL 수집 상태에서 실패 사유를 확인합니다.','수집·색인이 정상이어도 광고 노출이 보장되지는 않습니다. 운영 여부·심사·예산·비즈채널·연결URL을 계정에서 확인합니다.','AI 광고를 운영하면 랜딩의 실제 상품·사업 정보와 비즈채널 정보를 맞추고 테스트 전환을 발생시켜 수신을 확인합니다.','자연 검색 노출·AI 답변 출처·AI 지면의 유료 광고를 별도 집계합니다. 광고를 늘린 기간의 유입 증가를 SEO 효과로 돌리지 않습니다.'],toBe:'유료 광고와 자연 검색·AI 출처의 변화 원인을 구분할 수 있는 운영 기록',change:'노출 제한 원인을 더 정확히 찾고 채널별 예산·콘텐츠 개선을 판단할 수 있습니다.',kpi:'광고 수집/색인 상태 · 유료 클릭·전환·CPA · 자연 검색 실적 별도',verify:'전환 스크립트 존재가 아닌 실제 이벤트 수신 확인 · 광고 계정 보고서 대조',sources:['ads','aiAds','naverPerformance']});
  const order={action:0,manual:1,observed:2};
  const manualOrder=['measurement','title-heading','answer-content','google-ai-control'];
  const manualRank=(id:string)=>{const index=manualOrder.indexOf(id);return index<0?manualOrder.length:index;};
  tasks.sort((a,b)=>order[a.status]-order[b.status]||(a.status==='manual'&&b.status==='manual'?manualRank(a.id)-manualRank(b.id):0)||Number(b.priority==='high')-Number(a.priority==='high'));
  return {site,url,capturedAt:p?.capturedAt,hasTechnicalEvidence:!!s,tasks,reviewedAt:GROWTH_REVIEWED_AT};
}
export function growthBrief(report:MarketingReport,task:GrowthAction):string {
  const plan=buildGrowthPlan(report);
  return [`${task.title}`,`대상: ${plan.url||report.url}`,`분류: ${task.areas.join(' · ')} / ${task.channel}`,`담당: ${task.owner}`,`상태: ${GROWTH_STATUS[task.status]}`,`현재 근거: ${task.evidence}`,`수정 위치: ${task.location}`,'',...task.steps.map((s,i)=>`${i+1}. ${s}`),'',`TO-BE / 작성 틀: ${task.toBe}`,`수정 후 기대하는 변화: ${task.change}`,`확인할 KPI: ${task.kpi}`,`완료 확인: ${task.verify}`,...task.sources.map(id=>`${GROWTH_SOURCES[id].title}: ${GROWTH_SOURCES[id].url}`),`공식 문서 확인: ${GROWTH_REVIEWED_AT}`,GROWTH_SCOPE].join('\n');
}
