import * as cheerio from 'cheerio';
import {randomUUID} from 'node:crypto';
import {safeFetch,publicUrl} from './safeFetch';
import {AccessError} from './errors';
import type {Report,Check,Guide,Category,Goal} from '../src/types';
const source={title:{title:'Google · 검색 결과 제목',url:'https://developers.google.com/search/docs/appearance/title-link'},description:{title:'Google · 검색 설명',url:'https://developers.google.com/search/docs/appearance/snippet'},heading:{title:'W3C · 제목과 페이지 구조',url:'https://www.w3.org/WAI/tutorials/page-structure/headings/'},link:{title:'W3C · 링크 목적 이해',url:'https://www.w3.org/WAI/WCAG22/Understanding/link-purpose-in-context.html'},image:{title:'W3C · 이미지 대체 텍스트',url:'https://www.w3.org/WAI/tutorials/images/decision-tree/'},content:{title:'Google · 유용하고 신뢰할 수 있는 콘텐츠',url:'https://developers.google.com/search/docs/fundamentals/creating-helpful-content'},viewport:{title:'web.dev · 반응형 화면',url:'https://web.dev/articles/responsive-web-design-basics'},robots:{title:'Google · robots 메타 지시',url:'https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag'}};
export function normalizeUrl(value:string){return publicUrl(/^https?:\/\//i.test(value.trim())?value.trim():'https://'+value.trim()).href;}
export function analyzeHtml(html:string,url:string,goal:Goal):Report {
 const $=cheerio.load(html),clean=(v:string)=>v.replace(/\s+/g,' ').trim(),title=clean($('title').first().text()).slice(0,250),desc=clean($('meta[name="description" i]').attr('content')||'');
 const assets=$('script[src],link[href],img[src]').toArray().map(e=>$(e).attr('src')||$(e).attr('href')||'');
 const host=(domain:string)=>assets.some(v=>{try{const h=new URL(v,url).hostname;return h===domain||h.endsWith('.'+domain);}catch{return false;}});
 const platform=host('imweb.me')?'아임웹':host('echosting.cafe24.com')?'카페24':assets.some(v=>/\/wp-(content|includes)\//.test(v))?'WordPress':host('cdn.shopify.com')?'Shopify':'제작 도구 미확인';
 $('script,style,noscript,template,[hidden],[aria-hidden="true"]').remove();
 const body=clean($('body').text());if(body.length<80)throw new AccessError(422,'읽을 수 있는 본문이 부족해요. 로그인 없는 공개 페이지를 입력해 주세요. 동적으로 표시되는 내용은 이번 진단에서 읽지 못할 수 있어요.');
 const h1=$('h1').filter((_,e)=>clean($(e).text()).length>0),h2=$('h2,h3').filter((_,e)=>clean($(e).text()).length>0),paragraph=$('main p,article p,section p,body p').filter((_,e)=>clean($(e).text()).length>20).first();
 const links=$('a,button').filter((_,e)=>/문의|상담|신청|구매|예약|시작|가입|견적|장바구니|contact|buy|book|join|start/i.test(clean($(e).text()))),cta=links.first();
 const meaningful=links.filter((_,e)=>{const s=clean($(e).text());return s.length>2&&!/^(더 보기|자세히|클릭|확인|more|click here|join us)$/i.test(s);});
 const images=$('img'),missingAlt=images.filter((_,e)=>$(e).attr('alt')===undefined),viewport=$('meta[name="viewport" i]').attr('content')||'',robots=($('meta[name="robots" i]').attr('content')||'')+' '+($('meta[name="googlebot" i]').attr('content')||'');
 const hasContact=/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}|0\d{1,2}[- )]?\d{3,4}[- ]?\d{4}|사업자등록|대표자|고객센터/.test(body);
 const hasProof=/사례|후기|고객 평가|이용 방법|제공 범위|배송|반품|환불|운영시간|운영 시간/.test(body);
 const checks:Check[]=[
 {id:'title',category:'find',label:'페이지 제목',pass:!!title,weight:2},{id:'description',category:'find',label:'검색 설명',pass:desc.length>=15,weight:1},{id:'robots',category:'find',label:'HTML 색인 허용',pass:!/(^|[\s,])(noindex|none)($|[\s,])/i.test(robots),weight:2},
 {id:'heading',category:'first',label:'주요 제목 구조',pass:h1.length>0,weight:2},{id:'viewport',category:'first',label:'모바일 표시 설정',pass:/width\s*=\s*device-width/i.test(viewport),weight:1},
 {id:'sections',category:'clarity',label:'내용을 나누는 소제목',pass:h2.length>0,weight:1},{id:'description-text',category:'clarity',label:'설명 본문',pass:!!paragraph.length,weight:2},{id:'alt',category:'clarity',label:'이미지 alt 속성',pass:missingAlt.length===0,weight:1},
 {id:'contact',category:'trust',label:'연락·사업자 정보',pass:hasContact,weight:1},{id:'proof',category:'trust',label:'사례·이용 조건 관련 표현',pass:hasProof,weight:1},
 {id:'cta',category:'action',label:'다음 행동 안내',pass:links.length>0,weight:2},{id:'cta-label',category:'action',label:'목적을 설명하는 버튼 문구',pass:meaningful.length>0,weight:1}];
 const scores={} as Report['scores'];for(const k of ['find','first','clarity','trust','action'] as Category[]){const c=checks.filter(x=>x.category===k);scores[k]=Math.round(100*c.filter(x=>x.pass).reduce((s,x)=>s+x.weight,0)/c.reduce((s,x)=>s+x.weight,0));}
 function selector(e:ReturnType<typeof $>){const el=e.get(0);if(!el||!('tagName'in el))return '';const parts:string[]=[];let item=e.first();while(item.length){const id=item.attr('id');if(id&&/^[A-Za-z_][\w-]{0,150}$/.test(id)&&$('[id]').filter((_,n)=>$(n).attr('id')===id).length===1){parts.unshift('#'+id);break;}const node=item.get(0);if(!node||!('tagName'in node))break;parts.unshift(`${node.tagName}:nth-of-type(${item.prevAll(node.tagName).length+1})`);item=item.parent();}return parts.join(' > ').slice(0,800);}
 function location(e:ReturnType<typeof $>){if(!e.length)return '공개 원문에서 대상 위치를 확인하지 못했어요.';const region=e.closest('header,footer,main,nav').get(0);const r=region&&'tagName'in region?{header:'상단 메뉴',footer:'하단 정보',main:'주요 본문',nav:'탐색 메뉴'}[region.tagName]:'본문';const section=e.closest('section,article,.section_wrap'),head=clean(section.find('h1,h2,h3').first().text());return [r,head?`“${head.slice(0,60)}” 구역`:'',selector(e)].filter(Boolean).join(' · ');}
 function route(e:ReturnType<typeof $>,seo=false){if(platform==='아임웹'){if(seo)return ['디자인 모드 → 메뉴 관리에서 이 URL에 해당하는 메뉴의 설정을 여세요.','페이지별 SEO 제목·설명 항목을 현재 값과 대조하세요.'];const type=e.closest('[data-widget-type]').attr('data-widget-type');if(type==='code')return ['디자인 모드에서 원문이 있는 코드 위젯을 찾아 우클릭 → 코드 설정을 여세요.','기존 코드를 보관한 뒤 아래 원문과 선택자로 수정할 HTML을 찾으세요.'];if(e.closest('header').length)return ['디자인 모드 → 상단 디자인 편집에서 해당 상단 위젯을 선택하세요.','같은 문구가 PC·모바일 또는 고정 상단에 각각 있는지 확인하세요.'];return ['디자인 모드에서 이 URL의 페이지를 여세요.',`${type?`${type} 위젯`:'원문을 포함한 위젯'}의 설정을 열어 같은 문구를 찾으세요. 코드·상품·게시글이면 연결된 편집 화면에서 수정하세요.`];}if(platform==='WordPress')return ['관리자 → 페이지에서 해당 URL의 페이지를 여세요.','원문이 있는 블록을 찾으세요. SEO는 설치된 플러그인·테마에 따라 설정 위치가 달라요.'];return ['운영 관리자에서 해당 URL의 페이지 또는 콘텐츠 편집을 여세요.','아래 현재 값·위치 선택자로 대상 필드를 찾으세요. 공개 HTML만으로 관리자 메뉴·파일명을 확정할 수는 없어요.'];}
 const guides:Guide[]=[];
 const add=(id:string,category:Category,label:string,e:ReturnType<typeof $>,current:string,proposal:string,steps:string[],expected:string,boundary:string,metric:string,ref:keyof typeof source,priority:number,seo=false)=>guides.push({id,category,title:label,current,proposal,location:seo?'이 페이지의 검색 설정 / HTML head':location(e),selector:selector(e),steps:[...route(e,seo),...steps,'변경 전 내용을 보관하고 PC·모바일에서 미리보기하세요. 게시 후 같은 URL을 다시 진단하세요.'],expected,boundary,metric,source:source[ref],priority});
 const failed=(id:string)=>!checks.find(c=>c.id===id)!.pass;
 const name=title.split(/[|｜–—]/)[0]?.trim()||'[실제 브랜드명]',main=clean(h1.first().text())||'[실제로 제공하는 서비스]';
 if(failed('title'))add('title','find','검색에서 어떤 페이지인지 알려주세요',$('title').first(),title||'title을 읽지 못했어요.',`${name} | [핵심 서비스와 실제 대상]`,['제목 입력란에 서비스와 브랜드를 담으세요. 대괄호는 실제 정보로 채우세요.','공통 제목을 바꾸기 전에 다른 페이지에도 적용되는지 확인하세요.'],'검색엔진이 페이지 주제를 이해하고 검색 결과 제목을 구성할 자료를 정돈할 수 있어요.','검색 제목은 검색엔진이 다시 작성할 수 있어요. 순위·클릭 증가를 보장하지 않아요.','검색 제목 반영 여부, 같은 URL·검색어의 노출·클릭','title',goal==='search'?100:88,true);
 if(failed('description'))add('description','find','검색 설명에 서비스와 조건을 담으세요',$('meta[name="description" i]').first(),desc||'메타 설명을 읽지 못했어요.',`${name}에서 [대상 고객]을 위한 [실제 제공 내용]을 확인하세요. [이용 조건]과 [다음 행동]을 안내합니다.`,['이 URL의 메타 설명을 수정하세요. 본문에 없는 가격·성과·기간은 넣지 마세요.','저장 후 페이지 소스의 meta description과 값을 대조하세요.'],'방문 전에 서비스 범위와 조건을 이해할 수 있는 설명을 제공할 수 있어요.','작성한 설명의 그대로 노출이나 클릭 증가를 보장하지 않아요.','검색 설명 반영 여부와 동일 조건의 클릭률','description',goal==='search'?95:74,true);
 if(failed('robots'))add('robots','find','검색 제외 설정의 의도를 확인하세요',$('meta[name="robots" i]').first(),robots.trim(),'공개하려는 페이지에만 색인 제외 지시를 검토', ['공개 페이지인지 운영 담당자와 먼저 확인하세요.','공개 대상일 때만 noindex 또는 none을 출력하는 설정을 수정하세요. robots.txt나 회원 페이지의 접근 제한을 일괄 해제하지 마세요.','HTTP X-Robots-Tag와 검색 관리 도구의 색인 상태는 별도로 확인하세요.'],'공개 대상 페이지의 색인 제외 원인 중 하나를 해소할 수 있어요.','색인 허용이 실제 색인·노출을 보장하지 않아요. HTTP 헤더·robots.txt는 이번 범위에 포함되지 않아요.','게시 HTML과 Search Console·서치어드바이저 상태','robots',110);
 if(failed('heading'))add('heading','first','첫 화면의 대표 제목을 분명하게 만드세요',$('h1').first(),'수집한 HTML에서 내용 있는 H1을 확인하지 못했어요.',`${main} — [누구를 위한 어떤 도움인지]`,['첫 화면에서 핵심을 설명하는 실제 문구를 찾고 그 문구를 담당하는 요소를 수정하세요.','의미에 맞는 제목 수준을 지정하세요. 글자 크기만 키우거나 임의의 소제목을 H1으로 바꾸지 마세요.'],'페이지 주제와 내용의 계층을 이해하기 쉬워질 수 있어요.','H1 부재만으로 페이지가 나쁘다고 단정할 수 없고, H1 추가가 순위를 보장하지 않아요.','주요 제목·하위 제목 관계와 모바일 가독성','heading',90);
 if(failed('viewport'))add('viewport','first','휴대폰 화면 너비에 맞춰주세요',$('meta[name="viewport" i]').first(),viewport||'viewport 설정 미확인','width=device-width, initial-scale=1',['head의 viewport를 출력하는 설정을 확인하세요.','자동 출력되는 태그를 중복 추가하지 말고 원래 설정을 수정하세요. 사용자 확대는 허용하세요.'],'모바일에서 화면 전체가 작게 축소되는 원인 중 하나를 바로잡을 수 있어요.','CSS와 실제 기기 확인이 필요해요. 태그 하나로 반응형이나 전환율 개선을 보장하지 않아요.','가로 넘침·본문 크기·확대 및 입력 동작','viewport',99);
 if(failed('cta')||failed('cta-label'))add('cta','action','버튼을 누르면 무엇이 나오는지 알려주세요',cta,clean(cta.text())||'행동을 안내하는 버튼 문구 미확인',goal==='purchase'?'상품 구성과 구매 조건 확인':goal==='search'?'서비스 내용 자세히 보기':'상담 방법과 진행 과정 확인',['원문과 일치하는 버튼 하나를 선택하세요. 없으면 고객이 다음 행동을 결정하는 위치를 먼저 정하세요.','제안 문구를 실제 목적지에 맞게 수정하세요. 코드 위젯이면 링크·버튼 요소의 표시 텍스트를 수정하세요.','기존 링크를 확인하고 문구와 실제 이동 화면이 일치하는지 테스트하세요. 목적지 주소를 임의로 만들지 마세요.'],'클릭 후 이어질 행동을 이해하기 쉬워져 선택의 혼선을 줄이는 방향을 기대할 수 있어요.','문의·구매 증가 여부는 별도 실험이 필요해요. 클릭과 완료는 다른 지표예요.','버튼 클릭률과 클릭 후 문의·구매 완료율','link',goal==='search'?85:105);
 if(failed('contact'))add('contact','trust','누가 운영하는지 확인할 정보를 주세요',$('footer').first(),'연락·사업자 관련 표현을 수집 본문에서 확인하지 못했어요.','[실제 운영 주체] · [공개 가능한 연락 방법] · [응대 시간]',['하단 또는 문의 구역의 운영 주체·연락 정보를 확인하세요.','공개 가능한 실제 정보만 입력하고 연락 버튼의 동작을 확인하세요.'],'이용자가 운영 주체와 문의 방법을 확인할 수 있어요.','키워드 미발견은 정보의 실제 부재나 법적 의무 위반을 뜻하지 않아요.','연락 정보 노출·연결 동작·관련 문의 변화','content',83);
 if(failed('proof'))add('proof','trust','선택 전에 필요한 조건을 설명하세요',paragraph,clean(paragraph.text()).slice(0,900)||'이용 조건 관련 표현 미확인','제공 내용: [실제 범위]\n진행 방법: [실제 절차]\n확인할 조건: [기간·비용·예외]',['고객이 선택하기 전 확인해야 하는 실제 조건을 정리하세요.','사례를 추가한다면 공개 가능한 사실과 기준일을 함께 표시하세요. 없는 성과·후기를 만들지 마세요.'],'서비스 범위와 조건을 판단할 정보를 제공할 수 있어요.','설명 보완에 따른 전환 증가는 확인되지 않은 가설이에요.','같은 조건 질문의 반복·문의 후 이탈·완료율','content',70);
 if(failed('sections'))add('sections','clarity','긴 내용을 질문별로 나눠주세요',paragraph,clean(paragraph.text()).slice(0,900)||'소제목을 확인하지 못했어요.','어떤 서비스를 제공하나요?\n어떤 순서로 진행하나요?\n시작 전에 무엇을 확인해야 하나요?',['기존 설명을 보존하면서 실제 내용별로 소제목을 붙이세요.','소제목 바로 아래에 답을 두고 조건·예외를 생략하지 마세요.'],'내용의 관계를 파악하고 필요한 부분을 찾기 쉬운 구조를 만들 수 있어요.','AI 답변 인용이나 검색 순위를 보장하지 않아요.','제목 계층·내용 탐색·고객 질문 변화','heading',62);
 if(failed('alt'))add('alt','clarity','이미지의 역할에 맞는 설명을 확인하세요',missingAlt.first(),`alt 없는 이미지 ${missingAlt.length}개 · 첫 대상: ${missingAlt.first().attr('src')||'주소 미확인'}`,'정보 이미지: [실제로 전달하는 핵심 정보]\n장식 이미지: alt=""',['선택한 이미지가 정보·링크·장식 중 무엇인지 확인하세요.','정보 이미지는 내용을, 링크 이미지는 이동 목적을 설명하세요. 장식 이미지는 빈 alt를 사용할 수 있어요.'],'이미지를 볼 수 없는 상황에서도 필요한 정보를 전달할 수 있어요.','빈 alt는 장식 이미지에 적절할 수 있어요. 키워드 삽입으로 순위 상승을 보장하지 않아요.','이미지 역할과 alt 일치 여부','image',66);
 if(failed('description-text'))add('description-text','clarity','이미지 밖에도 핵심 설명을 제공하세요',paragraph,'수집 HTML에서 충분한 문단을 읽지 못했어요.',`${main}\n[실제 제공 범위와 이용 조건을 텍스트로 설명]`,['이미지 안에만 있는 핵심 설명이 있는지 확인하세요.','같은 의미를 읽을 수 있는 본문 텍스트로 제공하고 중복·접근성을 점검하세요.'],'기계가 읽을 수 있는 형태로 서비스 정보를 전달할 수 있어요.','이번 수집은 정적 HTML 기준이에요. 동적 화면의 실제 설명이 없다고 단정하지 않아요.','최종 HTML의 설명과 실제 화면 일치','content',80);
 return {id:randomUUID(),url,pageTitle:title||new URL(url).hostname,goal,createdAt:new Date().toISOString(),method:'pocket-static-v1',platform,scores,checks,guides:guides.sort((a,b)=>b.priority-a.priority),completed:[],coverage:'공개 HTML 1페이지의 규칙 기반 점검입니다. 5개 영역 점수는 확인 항목 충족률이며 검색 순위·매출·사이트 전체 품질 점수가 아닙니다. 로그인 화면, 동적 렌더링, 실제 관리자 설정·검색 실적은 확인하지 않습니다.'};
}
export async function analyzeWebsite(input:string,goal:Goal){const url=normalizeUrl(input);let response:Response;try{response=await safeFetch(url,{headers:{'user-agent':'MarketingScannerPocket/0.1 (+https://www.mktscanner.com)','accept':'text/html,application/xhtml+xml'}});}catch(e){if(e instanceof AccessError)throw e;throw new AccessError(422,'페이지를 읽지 못했어요. 주소와 공개 여부를 확인한 뒤 다시 시도해 주세요.');}if(!response.ok)throw new AccessError(422,`페이지가 HTTP ${response.status}로 응답했어요. 공개된 다른 페이지를 입력해 주세요.`);if(!/text\/html|application\/xhtml\+xml/i.test(response.headers.get('content-type')||''))throw new AccessError(422,'HTML 웹페이지를 입력해 주세요. 파일이나 API 주소는 진단할 수 없어요.');return analyzeHtml(await response.text(),response.url||url,goal);}
